### ISSUE TITLE
Compatibility with Gnome 3.38

### ISSUE THREAD

**Issue by k-kirill** [sbakker/Adwaita-Steven#3]
I do like this greenish version of Adwaita Dark, so many thanks for making it available.
However, there seem to be issues with it when running with Gnome 3.38. One of them is the wrong header bar height:
![wrong_header_height](https://user-images.githubusercontent.com/8539168/99889829-e6c83200-2c69-11eb-9d7a-54dd42e53db4.png)
So, could you please consider making the theme Gnome 3.38 compatible?
Thanks!

**Comment by sbakker** [comment]
Not sure which application seems to be misbehaving here... If I have to take a guess, it's the Clocks application, correct?
I'll have a look. I'm still on Gnome 3.36 (Fedora 32). Will try it on a Fedora 33 install.

**Comment by sbakker** [comment]
I just replicated it on a clean install of 3.38. So weird, because my tweaks only affect colours. I'm suspecting an issue with icon resource paths on the unpacked theme files that could be throwing sand in the works.

**Comment by sbakker** [comment]
I am seeing a `Could not load a pixbuf from icon theme` warning, so that could be related.

**Comment by sbakker** [comment]
I fixed all the `url("assets/...")` links, but this still doesn't fix it. I also created a `gtk.css` that only does a:
```
@import url("resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css");
```
Which should be an *exact* copy of the original Adwaita theme. The colours are indeed exactly the same, but it still creates the spacing around the icons in the Clock application.

**Comment by sbakker** [comment]
It also does something weird with the search box in the Files application.

**Comment by k-kirill** [comment]
I have few other themes installed and all of them are also affected, maybe due to libhandy being used in the header bar of gnome-clocks. Perhaps you need to rebuild your theme based on the fresh Adwaita anew :(

**Comment by sbakker** [comment]
There's not much I can do from the stock Adwaita, I'm afraid. All I basically do is unpack the Adwaita theme and modify some CSS.

**Comment by sbakker** [comment]
Seems like `libhandy` comes with a pre-installed set of theme files; let's see if I can rip those resources.

**Comment by sbakker** [comment]
Well, that was easy...
```
cd <THEME-DIRECTORY>
cd gtk-3.0
../scripts/xtract_resource /usr/lib64/libhandy-1.so.0 
perl -p -i -E 's{^(\@import url\("org/gtk/libgtk/.*"\);)$}{$1\n\@import url("sm/puri/handy/themes/Adwaita-dark.css");}' gtk.css
```
This fixes the sizing on the clock app. Nautilus search bar is still a bit weird though (frame is missing).

**Comment by k-kirill** [comment]
Wow, these commands did help fix the issue, so I can switch back to Adwaita-Tweaked. Thanks a lot for your help!
As to the weird Nautilus search bar, I can't notice anything suspicious or ugly enough to make me want to switch to stock Adwaita-dark :)

**Comment by sbakker** [comment]
I just updated the setup to also fiddle with GTK-4 theming...
